### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Shagon94** [megos/snipe-it-docker-compose#1]
example file:

```yml
version: '3'

services:

  app:
    image: snipe/snipe-it
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:80
    environment:
      - APP_KEY=base64:VUPOxPvnYAt/AOvyzbBDzlRZ1ujonyrsSWOw9AEt04I=
      - APP_URL=http://127.0.0.1:8080
      - MAIL_FROM_ADDR=you@example.com
      - MAIL_REPLYTO_ADDR=you@example.com
    depends_on:
      - db
      - mail
    volumes:
      - ./snipeit:/var/lib/snipeit

  db:
    image: mysql:5.6
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/var/lib/mysql

  mail:
    image: catatnight/postfix
    restart: unless-stopped
    environment:
      - maildomain=example.com
      - smtp_user=postfix:postfix

```

running and curling returns a 500, `.env` file is unchanged
